parameters:
#    wallr_reader.example.class: Wallr\APIBundle\Example

services:
#    wallr_reader.example:
#        class: %wallr_reader.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
